//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_of_Life.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color ColorPanelBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorPanelBG"]));
            }
            set {
                this["ColorPanelBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorGridLine {
            get {
                return ((global::System.Drawing.Color)(this["ColorGridLine"]));
            }
            set {
                this["ColorGridLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color ColorCellAlive {
            get {
                return ((global::System.Drawing.Color)(this["ColorCellAlive"]));
            }
            set {
                this["ColorCellAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorCellDead {
            get {
                return ((global::System.Drawing.Color)(this["ColorCellDead"]));
            }
            set {
                this["ColorCellDead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GridLineThickness {
            get {
                return ((int)(this["GridLineThickness"]));
            }
            set {
                this["GridLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int GridSegmentThickness {
            get {
                return ((int)(this["GridSegmentThickness"]));
            }
            set {
                this["GridSegmentThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GridSegmentLines {
            get {
                return ((int)(this["GridSegmentLines"]));
            }
            set {
                this["GridSegmentLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableGridLines {
            get {
                return ((bool)(this["EnableGridLines"]));
            }
            set {
                this["EnableGridLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSegmentLines {
            get {
                return ((bool)(this["EnableSegmentLines"]));
            }
            set {
                this["EnableSegmentLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorGridSegment {
            get {
                return ((global::System.Drawing.Color)(this["ColorGridSegment"]));
            }
            set {
                this["ColorGridSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RandSeed {
            get {
                return ((uint)(this["RandSeed"]));
            }
            set {
                this["RandSeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSeed {
            get {
                return ((bool)(this["UseSeed"]));
            }
            set {
                this["UseSeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public int RandAlive {
            get {
                return ((int)(this["RandAlive"]));
            }
            set {
                this["RandAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public int RandDead {
            get {
                return ((int)(this["RandDead"]));
            }
            set {
                this["RandDead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewNeighborCount {
            get {
                return ((bool)(this["ViewNeighborCount"]));
            }
            set {
                this["ViewNeighborCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewHeadsUpDisplay {
            get {
                return ((bool)(this["ViewHeadsUpDisplay"]));
            }
            set {
                this["ViewHeadsUpDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Color1Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color1Neighbor"]));
            }
            set {
                this["Color1Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color Color2Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color2Neighbor"]));
            }
            set {
                this["Color2Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color Color3Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color3Neighbor"]));
            }
            set {
                this["Color3Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Firebrick")]
        public global::System.Drawing.Color Color4Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color4Neighbor"]));
            }
            set {
                this["Color4Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color Color5Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color5Neighbor"]));
            }
            set {
                this["Color5Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color Color6Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color6Neighbor"]));
            }
            set {
                this["Color6Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color Color7Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color7Neighbor"]));
            }
            set {
                this["Color7Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Color8Neighbor {
            get {
                return ((global::System.Drawing.Color)(this["Color8Neighbor"]));
            }
            set {
                this["Color8Neighbor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font FontNeighbors {
            get {
                return ((global::System.Drawing.Font)(this["FontNeighbors"]));
            }
            set {
                this["FontNeighbors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color ColorBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackColor"]));
            }
            set {
                this["ColorBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontGen {
            get {
                return ((global::System.Drawing.Font)(this["FontGen"]));
            }
            set {
                this["FontGen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontCellCount {
            get {
                return ((global::System.Drawing.Font)(this["FontCellCount"]));
            }
            set {
                this["FontCellCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontBoundaryType {
            get {
                return ((global::System.Drawing.Font)(this["FontBoundaryType"]));
            }
            set {
                this["FontBoundaryType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontUniName {
            get {
                return ((global::System.Drawing.Font)(this["FontUniName"]));
            }
            set {
                this["FontUniName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontUniSize {
            get {
                return ((global::System.Drawing.Font)(this["FontUniSize"]));
            }
            set {
                this["FontUniSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontCellsAlive {
            get {
                return ((global::System.Drawing.Font)(this["FontCellsAlive"]));
            }
            set {
                this["FontCellsAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt, style=Bold")]
        public global::System.Drawing.Font FontCellsDead {
            get {
                return ((global::System.Drawing.Font)(this["FontCellsDead"]));
            }
            set {
                this["FontCellsDead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ColorCurrentGen {
            get {
                return ((global::System.Drawing.Color)(this["ColorCurrentGen"]));
            }
            set {
                this["ColorCurrentGen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ColorBoundaryType {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoundaryType"]));
            }
            set {
                this["ColorBoundaryType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ColorUniSize {
            get {
                return ((global::System.Drawing.Color)(this["ColorUniSize"]));
            }
            set {
                this["ColorUniSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ColorUniName {
            get {
                return ((global::System.Drawing.Color)(this["ColorUniName"]));
            }
            set {
                this["ColorUniName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color ColorCellCount {
            get {
                return ((global::System.Drawing.Color)(this["ColorCellCount"]));
            }
            set {
                this["ColorCellCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public global::System.Drawing.Color ColorCellCountAlive {
            get {
                return ((global::System.Drawing.Color)(this["ColorCellCountAlive"]));
            }
            set {
                this["ColorCellCountAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color ColorCellCountDead {
            get {
                return ((global::System.Drawing.Color)(this["ColorCellCountDead"]));
            }
            set {
                this["ColorCellCountDead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Torodial")]
        public string UniBoundaryType {
            get {
                return ((string)(this["UniBoundaryType"]));
            }
            set {
                this["UniBoundaryType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UniWidth {
            get {
                return ((int)(this["UniWidth"]));
            }
            set {
                this["UniWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UniHeight {
            get {
                return ((int)(this["UniHeight"]));
            }
            set {
                this["UniHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int UniSimSpeed {
            get {
                return ((int)(this["UniSimSpeed"]));
            }
            set {
                this["UniSimSpeed"] = value;
            }
        }
    }
}
